### ISSUE TITLE
OT-RegistrationService

### ISSUE THREAD

**Issue by frlzjosh** [Off-Top-App/off-top-python#26]
WHAT TO DO:
1. Create a microservice in any language/framework as long as the majority of the team approves, that will incorporate google Sign-in. 
2. This will require you to edit column names in the User Table, however, because we're in a migration phase you are better off creating a new database with a table called UserRegistration with all the required column names.

TAKS IS DONE WHEN:
1. You are able to successfully access OFF-TOP by using Google Sign-In and we are retaining your user information in the UserRegistration table. 

Here are resources:
1. Basics: https://www.youtube.com/watch?v=j_31hJtWjlw
2. Flutter plugin: https://pub.dev/packages/google_sign_in
3. Node.js back-end implementation: https://medium.com/@jackrobertscott/how-to-use-google-auth-api-with-node-js-888304f7e3a0
4. Flask: https://pythonhosted.org/Flask-GoogleLogin/

**Comment by tonynguyen98** [comment]
Can we move this over to the flutter repo?
